<?php

use \Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\ReplaceCommand;

const JOB_CRITERIA = ['skills', 'experience', 'certifications'];

function lb_jobs_form_alter(&$form, $form_state, $form_id) {

  $job_type = $form_state->getValue(['field_job_type']);

  foreach (JOB_CRITERIA as $crit) {

    $field = 'field_' . $crit;

    $form[$field]['#states']['visible'] = [
      ':input[name="field_job_type"]' => ['!value' => '_none']
    ];

    $form[$field]['#prefix'] = '<div id="' . $field  . '--ajax-wrapper">';
    $form[$field]['#suffix'] = '</div>';

    $form[$field]['widget']['#options'] = lb_jobs_options($crit, $job_type);
  }

  $form['field_job_type']['widget']['#ajax'] = [
    'callback' => 'lb_jobs_ajax_callback',
    'disable-refocus' => FALSE,
    'event' => 'change',
    'wrapper' => 'field-skills-ajax-wrapper',
    'progress' => [
      'type' => 'throbber',
      'message' => 'Fetching options...',
    ],
  ];
}

function lb_jobs_ajax_callback(array &$form, FormStateInterface $form_state) {

  $response = new AjaxResponse();

  foreach (JOB_CRITERIA as $crit) {

    $field = 'field_' . $crit;

    $response->addCommand(new ReplaceCommand('#' . $field . '--ajax-wrapper', ($form[$field])));
  }

  return $response;
}

function lb_jobs_options($vocab, $job_type) {

  $query = \Drupal::entityQuery('taxonomy_term');
  $query->condition('vid', $vocab);
  $query->condition('status', 1);
  $tids = $query->execute();
  $terms = \Drupal\taxonomy\Entity\Term::loadMultiple($tids);

  foreach ($terms as $t) {
    if ($t->get('field_job_type')->entity->id() == $job_type[0]['target_id']) {
      $options[$t->id()] = $t->name->value;
    }
  }

  return $options;
}
